name: gds-viewer

on:
  push:
  workflow_dispatch:

jobs:
  viewer:
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy GDS Viewer
        uses: TinyTapeout/tt-gds-action/static_viewer@tt10
        with:
          gds_path: gds/SAR-ADC-using-Sky130-PDK.gds.gz
